install.sh: xbps-install (void linux) support

diff --git a/.github/workflows/test-install.yml b/.github/workflows/test-install.yml
--- a/.github/workflows/test-install.yml
+++ b/.github/workflows/test-install.yml
@@ -182,6 +182,24 @@ jobs:
             exit 1
           fi
 
+  void-linux:
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/tags/v')
+    container: ghcr.io/void-linux/void-glibc:latest
+    steps:
+      - name: Test install
+        run: |-
+          set -e pipefail
+          xbps-install -yu curl
+          /bin/sh -c "$(curl -fsSL https://sq.io/install.sh)"
+          if [ $(sq version | awk '{print $1}') != "sq" ]; then
+            # NOTE: The Void package release is a manual process.
+            # Thus, the released version will not match this particular
+            # workflow release. We'll just do a simple test here.
+            echo "FAIL: sq install not working for some reason"
+            exit 1
+          fi
+
   windows-scoop:
     runs-on: windows-latest
     if: startsWith(github.ref, 'refs/tags/v')
